services:
  frontend:
    image: ghcr.io/lpl-team-6/caseauth-frontend:latest
    ports:
      - 4200:80
    depends_on:
      api:
        condition: service_started

  api:
    image: ghcr.io/lpl-team-6/caseauth-api:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      Database__Provider: Postgres
      ConnectionStrings__Postgres: >
        Host=db;
        Port=5432;
        Database=${POSTGRES_DB};
        Username=${POSTGRES_USER};
        Password=${POSTGRES_PASSWORD}

    ports:
      - 8080:8080

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  postgres_data:
